@if ($tsContetData)
    @foreach ($tsContetData as $content)
        @if ($content->layout == 'hero_slider')
            @include('partials.sections.hero-banner')
        @elseif($content->layout == 'logo_section')
            @include('partials.sections.logo-section')
        @elseif($content->layout == 'common_section')
            @include('partials.sections.common-section')
        @elseif($content->layout == 'zigzag_section')
            @include('partials.sections.zigzag-section')
        @elseif($content->layout == 'full_image_content')
            @include('partials.sections.full-image-content')
        @elseif($content->layout == 'page_grid_section')
            @include('partials.sections.page-grid-sectiont')
        @elseif($content->layout == 'testimonial_section')
            @include('partials.sections.testimonial-section')
        @elseif($content->layout == 'instagram_slider')
            @include('partials.sections.instagram-slider')
        @elseif($content->layout == 'inner_banner')
            @include('partials.sections.inner-banner')
        @elseif($content->layout == 'image_grid')
            @include('partials.sections.image-grid')
        @elseif($content->layout == 'content_with_slider')
            @include('partials.sections.content-with-slider')
        @endif
    @endforeach
@else
@endif
